import { bottlePlaceholder } from '../utils/placeholderImage';
import type { CreateProductInput } from '../validators/product.validator';

/**
 * Demo catalog for local development. Run with `npm run seed` (see
 * seed/run.ts). Images are on-brand generated placeholders, not stock
 * photography — swap `primaryImage`/`images` for real product photo
 * URLs once a real image pipeline exists; nothing else needs to change.
 */
function sizesFor(basePriceCents: number, stock: number): CreateProductInput['sizes'] {
  const split = [0.4, 0.35, 0.25].map((share) => Math.max(1, Math.round(stock * share)));
  return [
    { label: '30ml', volumeMl: 30, priceCents: Math.round(basePriceCents * 0.7), stock: split[0]! },
    { label: '50ml', volumeMl: 50, priceCents: basePriceCents, stock: split[1]! },
    { label: '100ml', volumeMl: 100, priceCents: Math.round(basePriceCents * 1.65), stock: split[2]! },
  ];
}

export const productSeeds: CreateProductInput[] = [
  {
    name: 'Ambre Noir',
    slug: 'ambre-noir',
    description:
      'A warm amber built around labdanum and dark vanilla, softened with a whisper of smoke. Composed to last from morning meetings into evening — one idea, worn close.',
    category: 'Eau de Parfum',
    gender: 'unisex',
    priceCents: 18500,
    sku: 'LP-AMB-001',
    stock: 40,
    sizes: sizesFor(18500, 40),
    primaryImage: bottlePlaceholder('#4a3728', '#f7f2ea'),
    images: [bottlePlaceholder('#4a3728', '#f7f2ea')],
    fragranceFamily: 'amber',
    topNotes: ['Bergamot', 'Pink Pepper'],
    heartNotes: ['Labdanum', 'Cistus'],
    baseNotes: ['Vanilla', 'Dark Amber', 'Smoked Woods'],
    ingredients: ['Alcohol Denat.', 'Parfum', 'Aqua', 'Limonene', 'Linalool'],
    rating: 4.8,
    reviewCount: 126,
    featured: false,
    bestSeller: true,
    newArrival: false,
  },
  {
    name: 'Jardin Blanc',
    slug: 'jardin-blanc',
    description:
      'White florals at first light — jasmine and tuberose held up by green stems rather than sweetness. Quiet, not powdery.',
    category: 'Eau de Toilette',
    gender: 'women',
    priceCents: 15500,
    salePriceCents: 12400,
    sku: 'LP-JAR-002',
    stock: 25,
    sizes: sizesFor(15500, 25),
    primaryImage: bottlePlaceholder('#8c6d4f', '#f4f1ec'),
    images: [bottlePlaceholder('#8c6d4f', '#f4f1ec')],
    fragranceFamily: 'floral',
    topNotes: ['Green Leaves', 'Bergamot'],
    heartNotes: ['Jasmine Sambac', 'Tuberose'],
    baseNotes: ['White Musk', 'Cedar'],
    ingredients: ['Alcohol Denat.', 'Parfum', 'Aqua', 'Benzyl Benzoate'],
    rating: 4.6,
    reviewCount: 84,
    featured: false,
    bestSeller: false,
    newArrival: false,
  },
  {
    name: 'Vétiver Fumé',
    slug: 'vetiver-fume',
    description:
      'Smoked vetiver over dry cedar, with a single line of bergamot to keep it from turning heavy. Built for someone who prefers restraint to projection.',
    category: 'Eau de Parfum',
    gender: 'men',
    priceCents: 19500,
    sku: 'LP-VET-003',
    stock: 3,
    sizes: sizesFor(19500, 3),
    primaryImage: bottlePlaceholder('#211d1a', '#e8dfd0'),
    images: [bottlePlaceholder('#211d1a', '#e8dfd0')],
    fragranceFamily: 'woody',
    topNotes: ['Bergamot', 'Black Pepper'],
    heartNotes: ['Vetiver', 'Smoked Tea'],
    baseNotes: ['Cedarwood', 'Vetiver Absolute'],
    ingredients: ['Alcohol Denat.', 'Parfum', 'Aqua', 'Citral'],
    rating: 4.9,
    reviewCount: 51,
    featured: false,
    bestSeller: false,
    newArrival: true,
  },
  {
    name: 'Lueur Dorée',
    slug: 'lueur-doree',
    description:
      'Golden oud and saffron, composed as a single dense accord rather than a progression. The house\u2019s most concentrated formula.',
    category: 'Parfum',
    gender: 'unisex',
    priceCents: 24500,
    sku: 'LP-LUE-004',
    stock: 0,
    sizes: sizesFor(24500, 0),
    primaryImage: bottlePlaceholder('#b08d57', '#f7f2ea'),
    images: [bottlePlaceholder('#b08d57', '#f7f2ea')],
    fragranceFamily: 'oriental',
    topNotes: ['Saffron', 'Bergamot'],
    heartNotes: ['Rose', 'Oud'],
    baseNotes: ['Amber', 'Sandalwood'],
    ingredients: ['Alcohol Denat.', 'Parfum', 'Aqua', 'Eugenol'],
    rating: 5,
    reviewCount: 19,
    featured: true,
    bestSeller: false,
    newArrival: false,
  },
  {
    name: 'Rose Cendrée',
    slug: 'rose-cendree',
    description:
      'A smoked rose — petals held over embers rather than pressed into powder. Sits close to the skin, warms over the day.',
    category: 'Eau de Parfum',
    gender: 'women',
    priceCents: 21500,
    sku: 'LP-ROS-005',
    stock: 60,
    sizes: sizesFor(21500, 60),
    primaryImage: bottlePlaceholder('#8c6d4f', '#fdfbf7'),
    images: [bottlePlaceholder('#8c6d4f', '#fdfbf7')],
    fragranceFamily: 'floral',
    topNotes: ['Pink Pepper', 'Bergamot'],
    heartNotes: ['Bulgarian Rose', 'Geranium'],
    baseNotes: ['Patchouli', 'Ambergris Accord'],
    ingredients: ['Alcohol Denat.', 'Parfum', 'Aqua', 'Geraniol'],
    rating: 4.9,
    reviewCount: 142,
    featured: false,
    bestSeller: true,
    newArrival: false,
  },
  {
    name: 'Cuir Sauvage',
    slug: 'cuir-sauvage',
    description:
      'Raw leather and birch tar, tempered with iris root. Built to feel worn-in from the first spray.',
    category: 'Parfum',
    gender: 'men',
    priceCents: 22500,
    sku: 'LP-CUI-006',
    stock: 30,
    sizes: sizesFor(22500, 30),
    primaryImage: bottlePlaceholder('#211d1a', '#f4f1ec'),
    images: [bottlePlaceholder('#211d1a', '#f4f1ec')],
    fragranceFamily: 'woody',
    topNotes: ['Birch Tar', 'Juniper'],
    heartNotes: ['Leather Accord', 'Iris Root'],
    baseNotes: ['Tobacco Leaf', 'Cedar'],
    ingredients: ['Alcohol Denat.', 'Parfum', 'Aqua', 'Coumarin'],
    rating: 4.7,
    reviewCount: 63,
    featured: true,
    bestSeller: false,
    newArrival: false,
  },
  {
    name: 'N\u00e9roli \u00c9clat',
    slug: 'neroli-eclat',
    description:
      'Bitter orange blossom over sun-warmed citrus peel. The lightest formula in the collection — worn for warm mornings.',
    category: 'Eau de Toilette',
    gender: 'unisex',
    priceCents: 16500,
    sku: 'LP-NER-007',
    stock: 22,
    sizes: sizesFor(16500, 22),
    primaryImage: bottlePlaceholder('#4a3728', '#e3c9a1'),
    images: [bottlePlaceholder('#4a3728', '#e3c9a1')],
    fragranceFamily: 'citrus',
    topNotes: ['Blood Orange', 'Petitgrain'],
    heartNotes: ['Neroli', 'Orange Blossom'],
    baseNotes: ['Light Musk', 'Cedar'],
    ingredients: ['Alcohol Denat.', 'Parfum', 'Aqua', 'Limonene'],
    rating: 4.5,
    reviewCount: 37,
    featured: false,
    bestSeller: false,
    newArrival: true,
  },
  {
    name: 'Santal Brum\u00e9',
    slug: 'santal-brume',
    description:
      'Creamy sandalwood suspended in a soft fog of iris and musk. One of the house\u2019s longest-wearing formulas.',
    category: 'Eau de Parfum',
    gender: 'men',
    priceCents: 20500,
    sku: 'LP-SAN-008',
    stock: 45,
    sizes: sizesFor(20500, 45),
    primaryImage: bottlePlaceholder('#b08d57', '#e8dfd0'),
    images: [bottlePlaceholder('#b08d57', '#e8dfd0')],
    fragranceFamily: 'woody',
    topNotes: ['Cardamom', 'Bergamot'],
    heartNotes: ['Sandalwood', 'Iris'],
    baseNotes: ['White Musk', 'Vanilla'],
    ingredients: ['Alcohol Denat.', 'Parfum', 'Aqua', 'Linalool'],
    rating: 4.8,
    reviewCount: 98,
    featured: false,
    bestSeller: true,
    newArrival: false,
  },
  {
    name: 'Iris Poudr\u00e9',
    slug: 'iris-poudre',
    description:
      'Powdery iris root over soft violet leaf — cool, composed, and quiet. A study in restraint.',
    category: 'Eau de Parfum',
    gender: 'women',
    priceCents: 19500,
    sku: 'LP-IRI-009',
    stock: 4,
    sizes: sizesFor(19500, 4),
    primaryImage: bottlePlaceholder('#8c6d4f', '#e3c9a1'),
    images: [bottlePlaceholder('#8c6d4f', '#e3c9a1')],
    fragranceFamily: 'floral',
    topNotes: ['Violet Leaf', 'Mandarin'],
    heartNotes: ['Iris Root', 'Heliotrope'],
    baseNotes: ['White Musk', 'Suede Accord'],
    ingredients: ['Alcohol Denat.', 'Parfum', 'Aqua', 'Benzyl Salicylate'],
    rating: 4.6,
    reviewCount: 28,
    featured: false,
    bestSeller: false,
    newArrival: true,
  },
  {
    name: 'Oud C\u00e9leste',
    slug: 'oud-celeste',
    description:
      'A restrained take on oud — cleaned of its sharper edges and set against cool rose. The house\u2019s most requested formula for evening.',
    category: 'Parfum',
    gender: 'unisex',
    priceCents: 28500,
    salePriceCents: 22800,
    sku: 'LP-OUD-010',
    stock: 18,
    sizes: sizesFor(28500, 18),
    primaryImage: bottlePlaceholder('#211d1a', '#d8c3a5'),
    images: [bottlePlaceholder('#211d1a', '#d8c3a5')],
    fragranceFamily: 'oriental',
    topNotes: ['Saffron', 'Rose'],
    heartNotes: ['Oud', 'Patchouli'],
    baseNotes: ['Amber', 'Musk'],
    ingredients: ['Alcohol Denat.', 'Parfum', 'Aqua', 'Eugenol'],
    rating: 4.9,
    reviewCount: 71,
    featured: true,
    bestSeller: false,
    newArrival: false,
  },
  {
    name: 'Fleur de Nuit',
    slug: 'fleur-de-nuit',
    description:
      'Night-blooming jasmine and tuberose, deepened with a low hum of vanilla. Composed for evenings, not projection.',
    category: 'Eau de Parfum',
    gender: 'women',
    priceCents: 20500,
    sku: 'LP-FLE-011',
    stock: 50,
    sizes: sizesFor(20500, 50),
    primaryImage: bottlePlaceholder('#4a3728', '#d8c3a5'),
    images: [bottlePlaceholder('#4a3728', '#d8c3a5')],
    fragranceFamily: 'floral',
    topNotes: ['Blackcurrant', 'Bergamot'],
    heartNotes: ['Night Jasmine', 'Tuberose'],
    baseNotes: ['Vanilla', 'Tonka Bean'],
    ingredients: ['Alcohol Denat.', 'Parfum', 'Aqua', 'Linalool'],
    rating: 4.8,
    reviewCount: 109,
    featured: false,
    bestSeller: true,
    newArrival: false,
  },
  {
    name: "Bois d'Hiver",
    slug: 'bois-dhiver',
    description:
      'Cold cedar and fir balsam, warmed by a low base of cashmeran. Built for the first cold week of the year.',
    category: 'Eau de Toilette',
    gender: 'men',
    priceCents: 17500,
    salePriceCents: 14000,
    sku: 'LP-BOI-012',
    stock: 33,
    sizes: sizesFor(17500, 33),
    primaryImage: bottlePlaceholder('#b08d57', '#f4f1ec'),
    images: [bottlePlaceholder('#b08d57', '#f4f1ec')],
    fragranceFamily: 'woody',
    topNotes: ['Fir Balsam', 'Juniper Berry'],
    heartNotes: ['Cedarwood', 'Cypress'],
    baseNotes: ['Cashmeran', 'Amber'],
    ingredients: ['Alcohol Denat.', 'Parfum', 'Aqua', 'Coumarin'],
    rating: 4.4,
    reviewCount: 22,
    featured: false,
    bestSeller: false,
    newArrival: true,
  },
  {
    name: 'Brise Marine',
    slug: 'brise-marine',
    description:
      'Sea salt and fig leaf over cool driftwood. The lightest, freshest formula in the collection — worn year-round.',
    category: 'Eau de Toilette',
    gender: 'unisex',
    priceCents: 15500,
    sku: 'LP-BRI-013',
    stock: 27,
    sizes: sizesFor(15500, 27),
    primaryImage: bottlePlaceholder('#9c8b76', '#f7f2ea'),
    images: [bottlePlaceholder('#9c8b76', '#f7f2ea')],
    fragranceFamily: 'fresh',
    topNotes: ['Sea Salt', 'Bergamot'],
    heartNotes: ['Fig Leaf', 'Marine Accord'],
    baseNotes: ['Driftwood', 'Ambroxan'],
    ingredients: ['Alcohol Denat.', 'Parfum', 'Aqua', 'Limonene'],
    rating: 4.5,
    reviewCount: 44,
    featured: false,
    bestSeller: false,
    newArrival: true,
  },
  {
    name: 'Musc Blanc',
    slug: 'musc-blanc',
    description:
      'Clean white musk built like a second skin — barely-there florals, no sweetness. The formula most often described as "smells like nothing, in the best way."',
    category: 'Eau de Parfum',
    gender: 'women',
    priceCents: 18500,
    sku: 'LP-MUS-014',
    stock: 38,
    sizes: sizesFor(18500, 38),
    primaryImage: bottlePlaceholder('#d8c3a5', '#fdfbf7'),
    images: [bottlePlaceholder('#d8c3a5', '#fdfbf7')],
    fragranceFamily: 'musk',
    topNotes: ['Pear', 'Pink Pepper'],
    heartNotes: ['White Musk', 'Lily of the Valley'],
    baseNotes: ['Ambrette Seed', 'Cedar'],
    ingredients: ['Alcohol Denat.', 'Parfum', 'Aqua', 'Hexyl Cinnamal'],
    rating: 4.7,
    reviewCount: 91,
    featured: false,
    bestSeller: true,
    newArrival: false,
  },
  {
    name: 'Poivre Ambr\u00e9',
    slug: 'poivre-ambre',
    description:
      'Black pepper and pink berries over a low amber base. Sharp at first spray, settles into something far warmer.',
    category: 'Eau de Parfum',
    gender: 'men',
    priceCents: 19500,
    sku: 'LP-POI-015',
    stock: 15,
    sizes: sizesFor(19500, 15),
    primaryImage: bottlePlaceholder('#4a3728', '#e8dfd0'),
    images: [bottlePlaceholder('#4a3728', '#e8dfd0')],
    fragranceFamily: 'other',
    topNotes: ['Black Pepper', 'Pink Berries'],
    heartNotes: ['Elemi', 'Cardamom'],
    baseNotes: ['Amber', 'Dry Woods'],
    ingredients: ['Alcohol Denat.', 'Parfum', 'Aqua', 'Limonene'],
    rating: 4.6,
    reviewCount: 33,
    featured: true,
    bestSeller: false,
    newArrival: false,
  },
];
